// <auto-generated />
using System;
using MercadoIgnis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoIgnis.Migrations
{
    [DbContext(typeof(MercadoIgnisContext))]
    partial class MercadoIgnisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MercadoIgnis.Models.Calificacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("Nota");

                    b.HasKey("ID");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("MercadoIgnis.Models.Especialidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("Nivel");

                    b.HasKey("ID");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("MercadoIgnis.Models.ProyectoIgnis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("Estado");

                    b.Property<DateTime>("FechaComienzo");

                    b.Property<DateTime>("FechaFinalizacion");

                    b.HasKey("ID");

                    b.ToTable("ProyectoIgnis");
                });

            modelBuilder.Entity("MercadoIgnis.Models.ProyectoPersonal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("FechaComienzo");

                    b.Property<DateTime>("FechaFinalizacion");

                    b.Property<string>("TipoDeProyecto");

                    b.HasKey("ID");

                    b.ToTable("ProyectoPersonal");
                });
#pragma warning restore 612, 618
        }
    }
}
