// <auto-generated />
using System;
using MercadoIgnis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProyectoIgnis.Migrations
{
    [DbContext(typeof(MercadoIgnisContext))]
    [Migration("20190530185516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MercadoIgnis.Models.Especialidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("Nivel");

                    b.HasKey("ID");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("MercadoIgnis.Models.ProyectoPersonal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Estado");

                    b.Property<DateTime>("FechaComienzo");

                    b.Property<DateTime>("FechaRealizacion");

                    b.Property<DateTime>("TiempoDeRealizacion");

                    b.Property<string>("TipoDeProyecto");

                    b.HasKey("ID");

                    b.ToTable("ProyectoPersonal");
                });
#pragma warning restore 612, 618
        }
    }
}
